/*criando o database e selecionando ele conforme última parte*/
CREATE SCHEMA SUCOS;

USE SUCOS; 

/*CRIANDO TABELA*/
CREATE TABLE TBCLIENTE (
	CPF VARCHAR(11),
	NOME VARCHAR(100),
	ENDERECO1 VARCHAR(150),
	ENDERECO2 VARCHAR(150),
	BAIROO VARCHAR(100),
	CIDADE VARCHAR(100),
	ESTADO VARCHAR(50),
	CEP VARCHAR(8),
	IDADE SMALLINT,
	SEXO VARCHAR(1),
	LIMITE_CREDITO FLOAT,
	VOLUME_COMPRA FLOAT,
	PRIMERA_COMPRA BIT(1)
);

CREATE TABLE TBPRODUTO (
	PRODUTO VARCHAR(20),
    NOME VARCHAR(150),
    EMBALAGEM VARCHAR(50),
    TAMANHO VARCHAR(50),
    SABOR VARCHAR(50),
    PRECO_LISTA FLOAT
);

CREATE TABLE TABELA_DE_VENDEDORES (
    MATRICULA varchar(5), 
    NOME varchar(100), 
    PERCENTUAL_COMISSAO float
);

/*APAGANDO TABELAS*/
DROP TABLE TABELA_DE_VENDEDORES;