USE SUCOS;

/*INSERINDO DADOS NA TABELA*/
INSERT INTO TBPRODUTO (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) 
			   VALUES ('1040107', 'Light - 350 ml - Melancia', 'Lata', '350 ml', 'Melancia', 4.56);
               
/*VENDO SE INCLUIU*/
SELECT * FROM TBPRODUTO;

/*NOVAS INSERÇÕES*/
INSERT INTO TBPRODUTO (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01);

INSERT INTO TBPRODUTO (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31);

INSERT INTO TBPRODUTO (
PRODUTO, 
NOME, 
EMBALAGEM, 
TAMANHO, 
SABOR, 
PRECO_LISTA) VALUES (
'1004327', 'Videira do Campo - 1,5 Litros - Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51);

/*TESTANDO AS NOVAS INSERÇÕES*/
SELECT * FROM TBPRODUTO;

/*INSERINDO PRODUTOS PARA TESTAR ALTERAÇÃO*/

INSERT INTO TBPRODUTO (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO TBPRODUTO (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

/*ALTERAÇÃO - O MYSQL POR PADRÃO VEM COM UMA CONFIGURAÇÃO QUE PERMITE APENAS ALTERAÇÕES BASEADAS 
EM CHAVE PRIMÁRIAS (NÃO UTILIZADAS POR ENQUANTO), PARA SER POSSÍVEL EXECUTAR DESABILITAMOS EM
EDIT > PREFERENCES > SQL EDITOR > SAFE UPDATES*/
UPDATE TBPRODUTO SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.46
WHERE PRODUTO = '544931';

UPDATE TBPRODUTO SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

/*TESTANDO AS ALTERAÇÕES*/
SELECT * FROM TBPRODUTO;

/*IMPORTANTE NUNCA SE ESQUECER DO WHERE, CASO EXECUTE SEM AFETARÁ TODAS LINHAS*/
UPDATE TBPRODUTO SET TAMANHO = '2 LITROS PADRÃO';

SELECT * FROM TBPRODUTO;

/*APAGANDO DADOS*/
/*ASSIM COMO NO UPDATE DEVEMOS USAR O WHERE PARA QUE NÃO EXCLUA TODOS*/
DELETE FROM TBPRODUTO WHERE PRODUTO = '1078680';

SELECT * FROM TBPRODUTO;

/*ALTERAÇÃO DE TABELAS*/
/*ADICIONANDO CHAVE PRIMARIA - UTILIZADA PARA UM VALOR ÚNICO*/
ALTER TABLE TBPRODUTO ADD PRIMARY KEY (PRODUTO); /*CADA PRODUTO DEVE TER UM 
                                                   CÓDIGO ÚNICO QUE NÃO PODE SE REPETIR*/

INSERT INTO TBPRODUTO (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

/*TESTE PARA MOSTRAR ERRO - NÃO POSSO INSERIR MESMA CHAVE PRIMARIA*/
INSERT INTO TBPRODUTO (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

ALTER TABLE TBCLIENTE ADD PRIMARY KEY (CPF);

ALTER TABLE TBCLIENTE ADD COLUMN (DATA_NASCIMENTO DATE);

ALTER TABLE TBCLIENTE RENAME COLUMN BAIROO TO BAIRRO;

ALTER TABLE TBCLIENTE RENAME COLUMN PRIMERA_COMPRA TO PRIMEIRA_COMPRA;

INSERT INTO TBCLIENTE (
CPF, 
NOME, 
ENDERECO1, 
ENDERECO2, 
BAIRRO, 
CIDADE, 
ESTADO, 
CEP, 
IDADE, 
SEXO, 
LIMITE_CREDITO, 
VOLUME_COMPRA, 
PRIMEIRA_COMPRA, 
DATA_NASCIMENTO) VALUES (
'00388934505', 
'João da Silva', 
'Rua projetada A número 10', 
'', 
'Vila Roman', 
'CARATINGA', 
'AM', 
'2222222', 
30, 
'M', 
10000.00, 
2000, 
0, 
'1989-10-05');

SELECT * FROM TBCLIENTE;